### ISSUE TITLE
Add Python3 support

### ISSUE THREAD

**Issue by freeman-lab** [binder-project/binder#12]
Requested by several users. We could update the base image to use Python 3, or maintain two base images (one for Py2 and one for Py3) and add this as an option during binder building.

**Comment by freeman-lab** [comment]
We're starting to work on this, the plan is to keep two separate base images, one based on Python 2 (the current base image) and one based on Python 3. 

And we'll add a bit to the build process on mybinder.org under "Configure dependencies" to let users specify the version (which will determine the base image used). The default selection will be Python 3.

This will probably change down the road as we refactor how kernels are specified / served, but should more or less satisfy users now. Seem reasonable @rgbkrk ?

cc @andrewosh

**Comment by rgbkrk** [comment]
Yeah, I was thinking that in the specification for the initial binder, they pick one of our base images (it may map to something nicer in the frontend).

```
{
  "name": "codeneuro-notebooks",
  "baseImage": "binder/python2",
  "repo": "https://github.com/CodeNeuro/notebooks",
  "requirements": "repo/requirements.txt",
  "notebooks": "repo/notebooks",
  "services": [
    {
      "name": "spark",
      "version": "1.4.1",
      "params": {
        "heap_mem": "4g",
        "stack_mem": "512m"
      }
    }
  ]
}
```

**Comment by andrewosh** [comment]
Definitely like specifying something like `baseImage`, though should we start moving in the direction of splitting up the kernels by changing `baseImage` to `kernels` and making it a list instead of a single string? Something like: 

```
{
  "name": "codeneuro-notebooks",
  "kernels": ["python2"]
  "repo": "https://github.com/CodeNeuro/notebooks",
  "requirements": "repo/requirements.txt",
  "notebooks": "repo/notebooks",
  "services": [
    {
      "name": "spark",
      "version": "1.4.1",
      "params": {
        "heap_mem": "4g",
        "stack_mem": "512m"
      }
    }
  ]
}
```

We'll only allow for a single kernel for now, but that will at least let us leave the schema in place when we make larger changes later.

**Comment by rgbkrk** [comment]
I'm tilted toward `baseImage` because of where our current tech lies, which is _probably_ going to involve an image that has multiple. Otherwise you're going to have your own map from an ordered list of kernels to the image that represents them.

When we break away to individual kernels that get launched, those will be individual images.

**Comment by andrewosh** [comment]
Hmm seems like that's putting an implementation detail into the spec that we're going to want to remove later. Whether a kernel (or multiple kernels) translates into a single base image, or multiple separate images, doesn't seem like something we should bake into the spec. 

I'm partial towards trying to define a more generic spec that will support what we want to build later, and then limiting ourselves to a restricted version of that now. I'm not really sure what you mean by "When we break away to individual kernels that get launched, those will be part of the image." though, so maybe I'm confused about something fundamental.

**Comment by andrewosh** [comment]
Added a Python 3 environment to Anaconda in e400c98d7361bd5e756ffa2f9d7244bca7167758, which resolves this issue. For now, we're going to support multiple kernels from within our single base image (which is feasible because we build/preload the base image offline), though in the future we plan on splitting these kernels up into several, lighter images.
