### ISSUE TITLE
Uh oh! Your Binder failed to build.

### ISSUE THREAD

**Issue by hainm** [binder-project/binder#22]
hi,

thanks for nice project. I got the error above when trying to build my package. The notice 'Uh oh! Your Binder failed to build' is not really informative. Where could I find the detail of the failing? thanks.

Hai

**Comment by andrewosh** [comment]
Hey @hainm, thanks for the feedback! 

We've added a bunch of support for better logging in #19, which is currently merged into master but isn't yet deployed in production (think I'll go ahead and reopen it because there are a few pesky bugs to fix first). Once we've redeployed the cluster (should do that tomorrow), you'll get a nice auto-updating box displaying your build logs whenever you do a build or want to check on the status of a Binder app. That should hopefully make it much easier to debug. 

I'm gonna close this issue though, because it's handled by #19 and #10. Thanks again

**Comment by hainm** [comment]
Thanks
