### ISSUE TITLE
Proxy target missing

### ISSUE THREAD

**Issue by hainm** [binder-project/binder#30]
hi,

currently, whenever open a link to my project in mybinder icon, I got 'Proxy target missing'. I need to refresh page to make it work. Is this your intention?

**Comment by hainm** [comment]
and the page refreshing took about 5-10 seconds.

**Comment by andrewosh** [comment]
Thanks for opening up an issue for this one @hainm. The problem here is that we're checking if the notebook container is running by seeing if Kubernetes has assigned its pod an IP. This is a fairly fast check (5-10s), but on occasion it assigns the IP before the container has fully launched, leading to the error. We can also check if the pod is in the "Ready" state, which is guaranteed to be correct, but takes considerably longer. 

An intermediate fix for this problem is to add javascript to the "Proxy target error" page, so that it automatically refreshes. That should be very quick to add, so we should have a fix in soon.

**Comment by rgbkrk** [comment]
> An intermediate fix for this problem is to add javascript to the "Proxy target error" page, so that it automatically refreshes. That should be very quick to add, so we should have a fix in soon.

I've been wishing for something better to override in this for the config proxy as well. :+1:

**Comment by minrk** [comment]
I just added support for [custom error pages](https://github.com/jupyter/configurable-http-proxy#custom-error-pages) in CHP, so you can specify what it does instead of the "Proxy target missing" message. If you guys want to give that a try, I'll cut a release if it seems like it's working.

**Comment by andrewosh** [comment]
The proxy server has been updated to use the the custom error pages @minrk added to the CHP, so this issue should be resolved in d2a949b7425951894a66205471049dee9503e293 (the 503 error page should auto-refresh).
