### ISSUE TITLE
Binder picking old images

### ISSUE THREAD

**Issue by etejedor** [binder-project/binder#52]
Hi,

I have observed that sometimes Binder uses old versions of our container image when spawning a new container. For instance, I just saw the issue in this container:

http://app.mybinder.org/1947057649/notebooks/index.ipynb

for the cernphsft/rootbinder image. That version is quite an old one, and it has been replaced (rebuilt) already several times.

Thank you,

Enric

**Comment by astrojuanlu** [comment]
I am experiencing the same issue with http://mybinder.org/repo/poliastro/poliastro.

**Comment by andrewosh** [comment]
Thanks for pointing this out. There was an issue a while back where an intermittent failure during the image preloading step (caused by a misbehaving node) was causing old images to be used in rare cases. 

I've modified the Kubernetes pod specification to always pull the latest image, and not depend on preloading, in https://github.com/binder-project/binder/commit/83362bcd6e169b8fb7c73e853e19479c6df09467 (which has been in use for a while, so hopefully there haven't been problems lately!). This should fix the issue
