### ISSUE TITLE
Deep Links to notebook files

### ISSUE THREAD

**Issue by NHDaly** [binder-project/binder#68]
Hi! Again, this service is amazing and is totally transforming the way I share code!! Amazing! :)

On that note -- **sharing** -- it would be nice if we could share a _deep link_ to a file within the repository.

For example, when I share a notebook file now, it looks something like this:

> Check out this code, Karl! Maybe you could try something like this?:
> https://github.com/NHDaly/jupyter-binder/blob/master/KarlNearestNeighbors.ipynb
> You can play around with it yourself in the browser! Click the "launch binder" button on my repo's home page, and open KarlNearestNeighbors.ipynb:
> https://github.com/NHDaly/jupyter-binder
> Or just click this link: http://mybinder.org/repo/nhdaly/jupyter-binder
> Lemme know what you think!

It would be suuuuper nice to be able to send just a single deep link:

> Check out this code, Karl! Maybe you could try something like this?:
> http://mybinder.org/repo/nhdaly/jupyter-binder/KarlNearestNeighbors.ipynb
> Lemme know what you think!

I'm not exactly sure what the structure of the link should look like, so that it isn't confused with the repo name. Maybe you could use the "#" trick:
http://mybinder.org/repo/nhdaly/jupyter-binder/#KarlNearestNeighbors.ipynb

:) Thanks!

**Comment by freeman-lab** [comment]
@NHDaly thanks for flagging this, and also for your enthusiasm and terrific examples! 

Funny enough, this was actually supported in the older version, but doesn't work now; luckily it should be an easy fix. We'll probably do it the way we did before, where a link like `http://mybinder.org/repo/nhdaly/jupyter-binder/index.ipynb` will just go straight to that location. Basically exactly your suggestion, but because org/repo names always have the same form, we don't even need the `#`. 

Will create an issue over on `binder-web` and add it back.

**Comment by NHDaly** [comment]
Sweeeeeet. Thanks! Haha maybe in my subconscious somewhere I knew that this worked once upon a time and that's what lead to the "idea". :) Thanks!

**Comment by freeman-lab** [comment]
Closing as this was added back.
